# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isBP',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isDN',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isFST',
        ),
    ]
