# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0003_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(default=2066839596, max_length=10),
            preserve_default=False,
        ),
    ]
