# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0003_post_isdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='isDB',
            new_name='De_Neve',
        ),
        migrations.AddField(
            model_name='post',
            name='Bplate',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Covel',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Feast',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
