# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0004_auto_20170219_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling.Post')),
            ],
        ),
    ]
